### ISSUE TITLE
Applay new file structure

### ISSUE THREAD

**Issue by LukaszOgrodnik** [adamsmietanka/aircraft-calculator#7]

**Comment by LukaszOgrodnik** [comment]
In the commit [12708f1](https://github.com/adamsmietanka/aircraft-calculator/commit/12708f18201e0dd3835308b06cdd9468e4a7a95c), there was a prototype solution pushed.

**Comment by adamsmietanka** [comment]
This was addressed in https://github.com/adamsmietanka/aircraft-calculator/pull/9
